### ISSUE TITLE
Allowing players to have a buffer of extra cards

### ISSUE THREAD

**Issue by darklordabc** [fcalife/artifart#14]
If a player has 5 cards, currently they dont recieve any more cards. I think there should be an internal tracker players to be "owed" more cards if they have a maximum of 5 already, this counter would increase everytime they should recieve a card but they couldnt because they were at max. When they have space for more cards, they should receive a card from this supply of owed cards. This effectively allows players to have more than 5 cards (even tho they can only ever see and use 5 cards).

**Comment by fcalife** [comment]
I actively dislike adding this because it is effectively a way to circumvent the 5-card limit. I think it is there for a reason, if you hoard cards, you risk overflowing, this is a mechanic present in every card game (except, ironically, artifact). If you want to increase the hand size, that's easily doable, but I think this mechanic is just confusing and a circumvention of the very rules we set in place.

**Comment by darklordabc** [comment]
Okay
