### ISSUE TITLE
Make a Turbo variety map

### ISSUE THREAD

**Issue by darklordabc** [fcalife/artifart#15]
Where players get cards ever 15 seconds. And whatever turbo related features you may feel like adding.

**Comment by fcalife** [comment]
Is this still necessary?
frankly speaking my plan regarding this was to simply not do anything
because I think 15s is too short and makes you start having to frantically manage cards more than play the game
it also doesn't give enough time for a "round" of card usage to resolve itself
in order to enjoy something you have to have a "refractory" period of sorts where the mind takes the time to laugh about what just happened and archive/process it
15s is too short and the things just pile up and become a blur of chaos
30-45s seems to be ideal for me
"give players the choice to play what they want" isn't a valid argument because they don't know what they want and will always pick turbo/fast/super/mega labeled modes, we have to figure out what's best for them
